export const metadata ={
    title: "About",
    description: "Generated by Meta",
}// заголовки

function About () {
    return (
        <div className="flex my-0 mx-auto">
            <h1 className="text-3xl font-bold underline ">About</h1>
        </div>
    )
}

export default About